require 'open-uri'
require 'pry'
require 'nokogiri'
require 'colorize'

require_relative '../lib/undercover_tourist_cli/attractions'
require_relative '../lib/undercover_tourist_cli/city'
require_relative '../lib/undercover_tourist_cli/scraper'
require_relative '../lib/undercover_tourist_cli/version'
require_relative '../lib/undercover_tourist_cli'